import { relations, sql } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

import { assetCategories, departments, organizations, users } from "./org";
import { assetCondition, assetStatus } from "./enums";

/**
 * The central entity.
 *
 * A "resource" (Room B2, a van, a projector) is deliberately NOT a separate
 * table — it is an asset with `is_bookable = true`. The spec describes it that
 * way ("marked as a shared bookable resource"), and it means a bookable room
 * still has a tag, a location, a maintenance history and an audit trail like any
 * other asset. `bookings.resource_id` therefore points here.
 *
 * `asset_tag` (AF-0001) is generated by a PostgreSQL SEQUENCE, not in app code —
 * see the migration. Two concurrent registrations can never collide on a tag.
 */
export const assets = pgTable(
  "assets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),

    /**
     * AF-0001, AF-0002 … minted by a PostgreSQL SEQUENCE.
     *
     * Declared here (not only in the migration) so Drizzle knows the column has a
     * database-side default and stops demanding one on insert. The sequence itself
     * is created in the migration — Drizzle cannot express CREATE SEQUENCE.
     *
     * nextval() is atomic, so two concurrent registrations cannot collide. A
     * read-max-then-increment in application code would.
     */
    assetTag: text("asset_tag")
      .notNull()
      .default(sql`'AF-' || lpad(nextval('asset_tag_seq')::text, 4, '0')`),

    name: text("name").notNull(),
    categoryId: uuid("category_id").references(() => assetCategories.id, {
      onDelete: "set null",
    }),

    serialNumber: text("serial_number"),
    acquisitionDate: date("acquisition_date"),

    // numeric, never float: money must not carry binary rounding error.
    // Used for ranking and reports only — AssetFlow does not touch accounting.
    acquisitionCost: numeric("acquisition_cost", { precision: 12, scale: 2 }),

    condition: assetCondition("condition").notNull().default("good"),
    location: text("location"),
    departmentId: uuid("department_id").references(() => departments.id, {
      onDelete: "set null",
    }),

    photoPath: text("photo_path"),

    /** Values for the owning category's `custom_fields` (e.g. warrantyMonths: 24). */
    customValues: jsonb("custom_values")
      .$type<Record<string, string | number>>()
      .notNull()
      .default(sql`'{}'::jsonb`),

    /** Makes this asset a bookable resource. Room B2 = true. */
    isBookable: boolean("is_bookable").notNull().default(false),

    status: assetStatus("status").notNull().default("available"),

    /** Drives the "nearing retirement" report. */
    retirementDate: date("retirement_date"),

    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique("assets_org_tag_unique").on(t.organizationId, t.assetTag),
    index("assets_org_idx").on(t.organizationId),
    index("assets_status_idx").on(t.status),
    index("assets_category_idx").on(t.categoryId),
    index("assets_department_idx").on(t.departmentId),
    // The spec's search keys: tag, serial. Both are looked up constantly.
    index("assets_serial_idx").on(t.serialNumber),
    index("assets_bookable_idx").on(t.isBookable),
  ],
);

export const assetsRelations = relations(assets, ({ one }) => ({
  organization: one(organizations, {
    fields: [assets.organizationId],
    references: [organizations.id],
  }),
  category: one(assetCategories, {
    fields: [assets.categoryId],
    references: [assetCategories.id],
  }),
  department: one(departments, {
    fields: [assets.departmentId],
    references: [departments.id],
  }),
}));
